package session

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"
)

// EntryType describes the kind of session entry.
type EntryType string

const (
	EntryTypeMessage    EntryType = "message"
	EntryTypeToolCall   EntryType = "tool_call"
	EntryTypeToolResult EntryType = "tool_result"
	EntryTypeMeta       EntryType = "meta"
)

// SessionEntry is a single node in the session DAG.
type SessionEntry struct {
	ID        string          `json:"id"`
	ParentID  string          `json:"parentId,omitempty"`
	Type      EntryType       `json:"type"`
	Role      string          `json:"role,omitempty"` // user, assistant, system
	Timestamp int64           `json:"timestamp"`
	Data      json.RawMessage `json:"data"`
}

// MessageData holds text message content.
type MessageData struct {
	Text string `json:"text"`
}

// ToolCallData holds a tool call's details.
type ToolCallData struct {
	Tool  string          `json:"tool"`
	ID    string          `json:"id"`
	Input json.RawMessage `json:"input"`
}

// ToolResultData holds the result of a tool call.
type ToolResultData struct {
	ToolCallID string `json:"tool_call_id"`
	Output     string `json:"output"`
	Error      string `json:"error,omitempty"`
	IsError    bool   `json:"is_error,omitempty"`
}

// Session holds a conversation session with DAG-structured entries.
type Session struct {
	ID      string
	AgentID string
	Key     string // channel + peer derived key

	entries  []SessionEntry
	entryMap map[string]*SessionEntry
	leafID   string // current leaf for history traversal
	store    *Store
}

// NewSession creates a new empty session.
func NewSession(agentID, key string) *Session {
	return &Session{
		ID:       generateID("ses"),
		AgentID:  agentID,
		Key:      key,
		entryMap: make(map[string]*SessionEntry),
	}
}

// Append adds an entry to the session.
func (s *Session) Append(entry SessionEntry) {
	if entry.ID == "" {
		entry.ID = generateID("e")
	}
	if entry.Timestamp == 0 {
		entry.Timestamp = time.Now().Unix()
	}
	if s.leafID != "" && entry.ParentID == "" {
		entry.ParentID = s.leafID
	}

	s.entries = append(s.entries, entry)
	s.entryMap[entry.ID] = &s.entries[len(s.entries)-1]
	s.leafID = entry.ID

	// Persist if store is set
	if s.store != nil {
		s.store.AppendEntry(s, entry)
	}
}

// History walks the DAG from root to current leaf and returns the path.
func (s *Session) History() []SessionEntry {
	if len(s.entries) == 0 {
		return nil
	}

	// Build path from leaf back to root
	var path []SessionEntry
	current := s.leafID
	for current != "" {
		entry, ok := s.entryMap[current]
		if !ok {
			break
		}
		path = append(path, *entry)
		current = entry.ParentID
	}

	// Reverse to get root→leaf order
	for i, j := 0, len(path)-1; i < j; i, j = i+1, j-1 {
		path[i], path[j] = path[j], path[i]
	}

	return path
}

// Entries returns all entries in append order.
func (s *Session) Entries() []SessionEntry {
	return s.entries
}

// LeafID returns the current leaf entry ID.
func (s *Session) LeafID() string {
	return s.leafID
}

// Branch moves the leaf pointer to the specified entry ID, creating a branch.
// New entries appended after this will have the branch point as their parent.
func (s *Session) Branch(entryID string) error {
	if _, ok := s.entryMap[entryID]; !ok {
		return fmt.Errorf("entry %q not found in session", entryID)
	}
	s.leafID = entryID
	return nil
}

// EstimateTokens returns a rough token estimate for the current history.
// Uses a simple heuristic of ~4 characters per token.
func (s *Session) EstimateTokens() int {
	history := s.History()
	totalChars := 0
	for _, entry := range history {
		totalChars += len(entry.Data)
		totalChars += len(entry.Role)
	}
	return totalChars / 4
}

// Compact replaces older history entries with a summary entry.
// It keeps the most recent keepEntries entries and replaces everything
// before them with a single summary meta entry.
// The summary text should be generated by the caller (typically by asking
// the LLM to summarize).
func (s *Session) Compact(summary string, keepEntries int) {
	history := s.History()
	if len(history) <= keepEntries {
		return // nothing to compact
	}

	// Split into old (to compact) and recent (to keep)
	cutoff := len(history) - keepEntries
	recentEntries := history[cutoff:]

	// Create summary meta entry
	summaryData, _ := json.Marshal(MessageData{Text: summary})
	summaryEntry := SessionEntry{
		ID:        generateID("compact"),
		Type:      EntryTypeMeta,
		Role:      "system",
		Timestamp: time.Now().Unix(),
		Data:      summaryData,
	}

	// Rebuild the session with summary + recent entries
	s.entries = nil
	s.entryMap = make(map[string]*SessionEntry)
	s.leafID = ""

	// Add summary entry
	s.entries = append(s.entries, summaryEntry)
	s.entryMap[summaryEntry.ID] = &s.entries[0]
	s.leafID = summaryEntry.ID

	// Add recent entries, re-parenting the first one to the summary
	for i, entry := range recentEntries {
		if i == 0 {
			entry.ParentID = summaryEntry.ID
		} else {
			entry.ParentID = recentEntries[i-1].ID
		}
		s.entries = append(s.entries, entry)
		s.entryMap[entry.ID] = &s.entries[len(s.entries)-1]
		s.leafID = entry.ID
	}

	// Rewrite the session file if store is set
	if s.store != nil {
		s.store.Rewrite(s)
	}
}

// SetStore associates a Store for automatic persistence.
func (s *Session) SetStore(store *Store) {
	s.store = store
}

// Helper constructors for common entry types

// UserMessageEntry creates a user message entry.
func UserMessageEntry(text string) SessionEntry {
	data, _ := json.Marshal(MessageData{Text: text})
	return SessionEntry{
		Type: EntryTypeMessage,
		Role: "user",
		Data: data,
	}
}

// AssistantMessageEntry creates an assistant message entry.
func AssistantMessageEntry(text string) SessionEntry {
	data, _ := json.Marshal(MessageData{Text: text})
	return SessionEntry{
		Type: EntryTypeMessage,
		Role: "assistant",
		Data: data,
	}
}

// ToolCallEntry creates a tool call entry.
func ToolCallEntry(toolCallID, toolName string, input json.RawMessage) SessionEntry {
	data, _ := json.Marshal(ToolCallData{
		Tool:  toolName,
		ID:    toolCallID,
		Input: input,
	})
	return SessionEntry{
		Type: EntryTypeToolCall,
		Data: data,
	}
}

// ToolResultEntry creates a tool result entry.
func ToolResultEntry(toolCallID, output, errMsg string) SessionEntry {
	data, _ := json.Marshal(ToolResultData{
		ToolCallID: toolCallID,
		Output:     output,
		Error:      errMsg,
		IsError:    errMsg != "",
	})
	return SessionEntry{
		Type: EntryTypeToolResult,
		Data: data,
	}
}

func generateID(prefix string) string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%s_%d", prefix, time.Now().UnixNano())
	}
	return prefix + "_" + hex.EncodeToString(b)
}
